import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import "./globals.css";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Voice Agent",
  description: "Generated by create next app",
   icons: {
    icon: "/favicon.png",
  },
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><StackProvider app={stackClientApp}><StackTheme>
     <Provider>
    {children}
      <Toaster />
      </Provider>
      </StackTheme></StackProvider></body>
    </html>
  );
}
